language: objective-c
env:
  - BUILD_TARGET=OSX
  - BUILD_TARGET=IPHONE
  - BUILD_TARGET=IPHONE_SIMULATOR
git:
  submodules: false
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git submodule update --init --recursive
install:
  - brew install mcpp
before_script:
  - export COMPILE_FOR_${BUILD_TARGET}=yes
script:
  - make -j3
  - python allTests.py --debug --env
notifications:
  email: travis-ci@zeroc.com
