language: objective-c
env:
- BUILD_TARGET=OSX
- BUILD_TARGET=IPHONE
- BUILD_TARGET=IPHONE_SIMULATOR
git:
  submodules: false
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- git submodule update --init --recursive
install:
- brew install mcpp
before_script:
- export COMPILE_FOR_${BUILD_TARGET}=yes
script:
- make -j3
- make test
notifications:
  slack:
    secure: gyjuHfic3SE+/0rJyXkRC0/KCFv37sj65XHnRLxAHG0oF7enY7OFxipJC7LPqzSp4HLRsSfHBKfSEcSKABcsFhhtunKfhB3aDAMwPf2Mg7XjDPqUEhfilf46Uayqn7KzHsqd9HrKayay+SKC0QE82yNeiDMLyVEF2td75zRyC8e+DbYvmEFDUcPgF6Rre2mIZRmm9j8y0kQFSb6EMp9NYDqssWfLlc4MQB9dc1KRVUoOjVfr7w6Il6h0AxBqlpIIeqdipYDwewA9oUWV9yH23SUtex+dLowAQLDjBr7Bf6cqgwuS4G4NI9eYqDIeYWkQN/8XFNP8NDLmd0jdKfPi+kzFxukKcBYO1syc6WuswQAkUDKu91A3ko9B9QlH/ePWoEdj8pIWxEaKo3vKU/mbHnT3HtBayEBu+cPFA8DcFAmPNeieQScrOBXek/A4Rqkq5ItUoCAoysQO66SwFRBUnfoLs1+fC5ek5a1gLBoeBafv2EJtfmnLqw9UFALdNmPoOWfuVvAsR/uoddw/hUXxoSe3STvSKdvkYjXIx/gKdfJUnzldN+jVN1/HU+ZxDZExaaqA79LnAWus3yc0x7jmZgmEzV9Zkba56nn2QqBhD+387wM3zg6taKt2Sk0A8kIBKzZ3L6D4pVHmSsctsBsQE+wpdKOQkpumOmCA8/Uktz4=
